### PR TITLE
fix: strictly define import to assist with browserify issues

### PR DESCRIPTION
**Pull request by bennyhobart**
Hey guys feel free to reject this or provide comment on how this can be improved, currently when i use serverless to deploy this code to lambda browserify has trouble resolving the imports of the resources

### CODE REVIEW

**Comment by michaelkantor** [comment]
I have some concerns... lets discuss them, and then we'll review in more detail.

1. The Platform API can not be access via a browser as this API is very deliberately not CORS friendly. The Platform API is an admin/super user level access intended for server-to-server operations where higher security is available.
2. Browserify as best I'm aware is solely for use in browsers.

You can probably see where this is going.  If you have a use case that I'm missing, please let me know.  If your looking for APIs for use from the browser, please see [Layer WebSDK](github.com/layerhq/layer-websdk).

**Comment by bennyhobart** [comment]
Your first concern is completely legitimate, my aim isn't to use this API in the browser

re 2: Currently https://github.com/serverless/serverless uses Browserify to bundle code before deployment to AWS which is why i bring this up. Currently this is the only technology I am aware of that does this, but I wouldn't be surprised if there are more.

If we can match that use case and up code quality in the process I don't see why not

**Comment by nilgradisnik** [comment]
That's fair. Could you also remove that `RESOURCES` variable from the code since it's not needed?
Then I can proceed to merge this.

**Comment by bennyhobart** [comment]
just removed resources, thanks for the hasty response guys love your work

**Pull request merged**
